name: Deploy MyToken

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npx hardhat compile
      - run: npx hardhat run scripts/deploy.js --network goerli
        env:
          GOERLI_RPC_URL: ${{ secrets.GOERLI_RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
